import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Toaster } from "sonner";
import "./globals.css";
import { AuthSessionProvider } from "@/components/auth/employee-session-provider";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
	title: "Parruchiere Prova",
	description: "Generated by DF",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">
				<AuthSessionProvider>
					<Navbar />
					{children}
					<Toaster richColors position="bottom-right" />
				</AuthSessionProvider>
			</body>
		</html>
	);
}
