import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import { EmployeeSessionProvider } from "@/components/auth/employee-session-provider";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
	title: "Parruchiere Prova",
	description: "Generated by DF",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">
				<EmployeeSessionProvider>
					<Navbar />
					{children}
					<Toaster richColors position="bottom-right" />
				</EmployeeSessionProvider>
			</body>
		</html>
	);
}
